Location model
BharatShukla30/neighborhood pull request #6
Opened 2023-03-07 05:56 UTC by Parmeshk7

2023-03-07 07:35 UTC, BharatShukla30 requested changes

2023-03-07 07:35 UTC, BharatShukla30 commented on model/Location.py
> +class Location(db.Model):
Change class name to User_location, change file name too

2023-03-07 07:35 UTC, BharatShukla30 commented on model/User.py
> +    # location = db.Column(db.String(100))
Remove this completely no need to comment this code

2023-03-07 07:35 UTC, BharatShukla30 commented on main.py
> +from model.Location import db, Location
Change accordingly

2023-03-07 07:35 UTC, BharatShukla30 commented on main.py
> +        #####   Added the City and State Attributes also
no need of comment here the variables name are sufficient

2023-03-07 07:35 UTC, BharatShukla30 commented on main.py
> +            #Adding the Entries into the db
remove comment, not needed code self explainatory.

2023-03-07 07:35 UTC, BharatShukla30 commented on main.py
> +        nearest_user_latitude = u.location.split(', ')[0]
what is the change here?

2023-03-07 07:42 UTC, Parmeshk7 commented on model/Location.py
> +class Location(db.Model):
Done

2023-03-07 07:42 UTC, Parmeshk7 commented on model/User.py
> +    # location = db.Column(db.String(100))
Done

2023-03-07 07:42 UTC, Parmeshk7 commented on main.py
> +from model.Location import db, Location
Done

2023-03-07 07:42 UTC, Parmeshk7 commented on main.py
> +        #####   Added the City and State Attributes also
Done

2023-03-07 07:42 UTC, Parmeshk7 commented on main.py
> +            #Adding the Entries into the db
Done

2023-03-07 07:43 UTC, Parmeshk7 commented on main.py
> +        nearest_user_latitude = u.location.split(', ')[0]
Actually I am not sure about the value that is stored in location variable, like how it actually representing the coordinates.

2023-04-14 12:39 UTC, closed without merging

2023-04-14 12:39 UTC, BharatShukla30 commented
Not needed anymore