add check unique_username functionality
BharatShukla30/neighborhood pull request #9
Opened 2023-04-18 18:57 UTC by akg07

2023-04-23 18:51 UTC, BharatShukla30 requested changes

2023-04-23 18:51 UTC, BharatShukla30 commented on routers/LoginRouter.py
> +        print('from request', username)
remove the print statement

2023-04-23 18:51 UTC, BharatShukla30 commented on model/User.py
> +    @staticmethod
why static? wont we make an object of the User class and then only call this method?? Also why is it in the user class? This method needs to be just called once when registering should just be a method call while doing registration

2023-05-24 20:02 UTC, akg07 commented
removed print messaged

2023-05-24 20:03 UTC, BharatShukla30 approved these changes

2023-05-24 20:03 UTC, merged